// @ts-nocheck -- skip type checking
import * as docs_10 from "../content/docs/use-genui-summarizer.mdx?collection=docs"
import * as docs_9 from "../content/docs/use-genui-hybrid-llm.mdx?collection=docs"
import * as docs_8 from "../content/docs/index.mdx?collection=docs"
import * as docs_7 from "../content/docs/genui-textarea.mdx?collection=docs"
import * as docs_6 from "../content/docs/genui-summarize-block.mdx?collection=docs"
import * as docs_5 from "../content/docs/genui-status.mdx?collection=docs"
import * as docs_4 from "../content/docs/genui-sonner.mdx?collection=docs"
import * as docs_3 from "../content/docs/genui-provider.mdx?collection=docs"
import * as docs_2 from "../content/docs/genui-input.mdx?collection=docs"
import * as docs_1 from "../content/docs/genui-i18n-text.mdx?collection=docs"
import * as docs_0 from "../content/docs/genui-human-verification.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"genui-human-verification.mdx","fullPath":"content/docs/genui-human-verification.mdx"}, data: docs_0 }, { info: {"path":"genui-i18n-text.mdx","fullPath":"content/docs/genui-i18n-text.mdx"}, data: docs_1 }, { info: {"path":"genui-input.mdx","fullPath":"content/docs/genui-input.mdx"}, data: docs_2 }, { info: {"path":"genui-provider.mdx","fullPath":"content/docs/genui-provider.mdx"}, data: docs_3 }, { info: {"path":"genui-sonner.mdx","fullPath":"content/docs/genui-sonner.mdx"}, data: docs_4 }, { info: {"path":"genui-status.mdx","fullPath":"content/docs/genui-status.mdx"}, data: docs_5 }, { info: {"path":"genui-summarize-block.mdx","fullPath":"content/docs/genui-summarize-block.mdx"}, data: docs_6 }, { info: {"path":"genui-textarea.mdx","fullPath":"content/docs/genui-textarea.mdx"}, data: docs_7 }, { info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_8 }, { info: {"path":"use-genui-hybrid-llm.mdx","fullPath":"content/docs/use-genui-hybrid-llm.mdx"}, data: docs_9 }, { info: {"path":"use-genui-summarizer.mdx","fullPath":"content/docs/use-genui-summarizer.mdx"}, data: docs_10 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"GenCN UI","pages":["---Introduction---","index","---Components---","genui-provider","genui-sonner","genui-input","genui-status","genui-textarea","genui-i18n-text","genui-summarize-block","genui-human-verification","---Hooks---","use-genui-summarizer","use-genui-hybrid-llm"],"description":"The Generative AI based Shadcn UI Component Library","root":true,"icon":"Building"}}])